// Code generated by "stringer -type=Status"; DO NOT EDIT.

package room

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_FINISHED-0]
	_ = x[DRAW-1]
	_ = x[P1_WON-2]
	_ = x[P2_WON-3]
}

const _Status_name = "NOT_FINISHEDDRAWP1_WONP2_WON"

var _Status_index = [...]uint8{0, 12, 16, 22, 28}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
