// Code generated by "stringer -type=Tile"; DO NOT EDIT.

package lobby

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A-0]
	_ = x[B-1]
	_ = x[C-2]
	_ = x[D-3]
	_ = x[E-4]
	_ = x[F-5]
	_ = x[G-6]
	_ = x[H-7]
	_ = x[I-8]
}

const _Tile_name = "ABCDEFGHI"

var _Tile_index = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

func (i Tile) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Tile_index)-1 {
		return "Tile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tile_name[_Tile_index[idx]:_Tile_index[idx+1]]
}
